backend/miproyecto/src/Entity/Empresas.php
<?php

namespace App\Entity;

use App\Repository\EmpresasRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmpresasRepository::class)
 */
class Empresas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $Email;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_sector;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getIdSector(): ?int
    {
        return $this->id_sector;
    }

    public function setIdSector(int $id_sector): self
    {
        $this->id_sector = $id_sector;

        return $this;
    }
}

backend/miproyecto/src/Entity/Usuariossectores.php
<?php

namespace App\Entity;

use App\Repository\UsuariossectoresRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UsuariossectoresRepository::class)
 */
class Usuariossectores
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_usuario;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_sector;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUsuario(): ?int
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(int $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    public function getIdSector(): ?int
    {
        return $this->id_sector;
    }

    public function setIdSector(int $id_sector): self
    {
        $this->id_sector = $id_sector;

        return $this;
    }
}

backend/miproyecto/templates/asignar_sector.html.twig
{% extends 'base.html.twig' %}
        {% block stylesheets %}
        {{parent()}}

        {% endblock %}
        
        {% block body %}
        
       
         <h5> ASIGNAR SECTOR A: {{ usuario.usuario }} </h5>

        <form action="{{ path ('asignar' , {'id' : usuario.id } ) }}" name="nuevo">
                <label class="form-label" for="sector">Sector: </label>
                <select class="form-control" name="sector">
                {% for sector in sectores %}
                        <option value="{{sector.id}}"> {{sector.nombre}}</option>
                {% endfor %}
                </select>

                <input class="mt-3 mb-3 w-100" type="submit" value="Asignar" name="crear">
        </form>


        <a href="{{('/usuarios')}}"><button>Atrás</button></a>
        
        {% endblock %}
        {% block javascripts %}

        {% endblock %}

backend/miproyecto/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"> 
        <!-- Bootstrap CSS -->
        
        <link href="{{ asset ('css/bootstrap.css') }}" rel="stylesheet" >
        <link href="{{ asset ('estilo.css') }}" rel="stylesheet" >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
         <script src= "{{ asset ('js/jquery-3.6.0.min.js')}}"></script>
         <script src="{{ asset ('js/myjs.js')}}"></script>
        <title>{% block title %}PRINCIPAL!{% endblock %}</title>
        {% block stylesheets %}
        
        {% endblock %}
    </head>
    <body> 
    
         <h3 class="title-menu">Proyecto Empresas </h3>
        <nav class="menu" id="mimenu">
        
                <a role="button" class="icon-menu" onclick="myFunction()">
                    <i class="fa fa-bars"></i>
                </a>

        {% if app.session.get('usuario') %}   

                <a class="menu-list" href="{{('/sectores')}}">SECTORES</a>
                <a class="menu-list" href="{{('/empresas')}}">EMPRESAS</a>
                <a class="menu-list" href="{{('/usuarios')}}">USUARIOS</a>
                
            <div class="sesion">
            Bienvenid@ {{app.session.get('usuario')}}
             <button ><a  href="{{'/logout'}}">LOGOUT</a></button> 
            </div>
        
        {% else %}
                <a class="menu-list" href="{{('/')}}">CRUD EMPRESAS/SECTORES</a>
                <a class="menu-list" href="{{('/monedas')}}">API CAMBIO DE MONEDAS</a>
                <a class="menu-list" href="{{('/formulario')}}">PARTE FRONTEND (FORMULARIO)</a>
        {% endif %}

        </nav>
        {% block body %}{% endblock %}
        {% block javascripts %}
        
        
       
        {% endblock %}
    </body>
</html>

backend/miproyecto/templates/empresas.html.twig
{% extends 'base.html.twig' %}
        {% block stylesheets %}
        {{parent()}}

        {% endblock %}



        {% block body %}
        
        <h5> LISTADO DE EMPRESAS </h5>
        
        
        {% if app.session.get('rol') == 'admin' %}
        <form action="{{('/empresas_sector')}}" name="buscar_sector">
                <label for="buscar_sector">Buscar por sector:</label>
                <select name="buscarid">
                  {% for sector in sectores %}
                        <option value="{{sector.id}}"> {{sector.nombre }} </option>
                 {% endfor %}
                </select>
                <input type="submit" value="Buscar" name="buscarsector">
        </form>
        {% endif %}
        
        <table class="table-responsive-sm table" >
                <thead class="table-title">
                        <tr>
                            <th>Empresa</th>
                            <th>Email</th>
                            <th>Sector de la empresa</th>
                            <th></th>
                        </tr>
                </thead>
                <tbody>
                {% if empresas_id is defined %}
                       
                        {% for empresa in empresas_id %}
                                <tr>

                                    <td>{{ empresa.nombre }} </td>
                                    <td>{{ empresa.email }}  </td>
                                       {% for sector in sectores %}
                                        {% if sector.id == empresa.idSector %}
                                        <td> {{ sector.nombre }} </td>
                                        {% endif %}
                                  
                                        {% endfor %}  
                                        
                                        <!-- solo admin -->
                                        {% if app.session.get('rol') == 'admin' %}
                                        <td>
                                                <a href="{{ path ('editar_empresa' , {'id' : empresa.id }) }}"><button class="btn btn-secondary"> <i class="fa fa-edit"></i> Editar</button></a> 
                                                <a href="{{ path ('eliminar_empresa' , {'id' : empresa.id }) }}"><button class="btn btn-secondary"> <i class="fa fa-minus-circle "></i> Eliminar</button></a>
                                        </td>
                                        {% endif %}
                                        
                                </tr> 


                        {% endfor %}  
                {% else %}
                        {% for empresa in empresas %}
                                <tr>
                                {% if app.session.get('rol') == 'admin' %}
                                    <td>{{ empresa.nombre }} </td>
                                    <td>{{ empresa.email }}  </td>
                                       {% for sector in sectores %}
                                        {% if sector.id == empresa.idSector %}
                                        <td> {{ sector.nombre }} </td>
                                        {% endif %}
                                         
                                        {% endfor %}
                                        <!--si el usuario es cliente -->

                                        {% else %} 
                                                {% for mi_sector in mis_sectores %}
                                                {% for sector in sectores %}
                                                        {% if empresa.idSector == sector.id %}
                                                        {% if sector.id == mi_sector.idSector %}
                                                        <tr>
                                                                <td>{{ empresa.nombre }} </td>
                                                                <td>{{ empresa.email }}  </td>
                                                                <td> {{ sector.nombre }} </td>
                                                        </tr>
                                                        {% endif %}
                                                        {% endif %}
                                                {% endfor %}
                                                {% endfor %}
                                {% endif %}
                                        <!-- solo admin -->
                                        {% if app.session.get('rol') == 'admin' %}
                                        <td>
                                                <a href="{{ path ('editar_empresa' , {'id' : empresa.id }) }}"><button claa="btn btn-secondary"> <i class="fa fa-edit"></i> Editar</button></a> 
                                                <a href="{{ path ('eliminar_empresa' , {'id' : empresa.id }) }}"><button claa="btn btn-secondary"> <i class="fa fa-minus-circle "></i> Eliminar</button></a>
                                        </td>
                                        {% endif %}
                                        
                                </tr> 


                        {% endfor %}  
                {% endif %}    
                </tbody>
        </table>


        {% if app.session.get('rol') == 'admin' %}
        <a href="{{('/nueva_empresa')}}"><button>Nueva empresa</button></a>
        {% endif %}


        {% endblock %}
        {% block javascripts %}

        {% endblock %}

backend/miproyecto/templates/login.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    <h5>LOGIN</h5>
    
    <form action="{{ ('/logearse') }}">
        <label class="form-label" for="usuario" >Usuario: * </label>
        <input class=" form-control" type="usuario" name="usuario" required >
        <label class=" form-label" for="pass"> Contraseña: *</label>
        <input class=" form-control" type="password" name="pass" required>

        <input class="mt-3 w-100" type="submit" value="Entrar">
    </form>
    
{% endblock %}

{% block javascripts %}
   
{% endblock %}

backend/miproyecto/templates/nueva_empresa.html.twig
{% extends 'base.html.twig' %}
        {% block stylesheets %}
        {{parent()}}

        {% endblock %}
        

        {% block body %}

        {% if empresa is defined %}
         <h5> EDITAR EMPRESA  </h5>
        {% else %}
        <h5> NUEVA EMPRESA  </h5>
         {% endif %}
        
        <form 
                 {% if empresa is defined %}
                 action="{{ path ('modifico_empresa', {'id' : empresa.id } )}}" 
                 {% else %}
                  action="{{('/crear_empresa')}}" 
                  {% endif %}
                  name="nuevo">
                
                <label class=" form-label" for="nombre">Nombre de la empresa: *</label>
                <input class=" form-control" type="text" name="nombre" 
                        {% if empresa is defined %}
                                value="{{empresa.nombre}}"
                        {% endif %}
                        required>
                <label class=" form-label"  for="email">Email de la empresa: *</label>
                <input class=" form-control" type="text" name="email" 
                        {% if empresa is defined %}
                                value="{{empresa.email}}"
                        {% endif %}
                        required>
                <label class=" form-label"  for="sector">Sector de la empresa: </label>
                
                <select class=" form-control" name="sector">
                        {% for sector in sectores %}
                                <option value="{{sector.id }}"
                                {% if empresa is defined %}
                                        {% if empresa.idSector == sector.id %}
                                                selected
                                        {% endif %}
                                {% endif %}
                                > {{sector.nombre}}</option>
                        {% endfor %}
                </select>
                <input class="mt-3 mb-3 w-100" type="submit" value="Crear sector" name="crear">
        </form>

        
        <a href="{{('/empresas')}}"><button>Atrás</button></a>
        {% endblock %}
        {% block javascripts %}

        {% endblock %}

backend/miproyecto/templates/nuevo_sector.html.twig
{% extends 'base.html.twig' %}
        {% block stylesheets %}
        {{parent()}}

        {% endblock %}
        

        {% block body %}
        
       
        {% if sector is defined %}
         <h5> EDITAR SERCTOR  </h5>
        {% else %}
         <h5> NUEVO SERCTOR  </h5>
         {% endif %}
        <form 
          {% if sector is defined %} 
                action="{{ path ('modifico_sector', {'id' : sector.id } )}}" 
                {% else %}
                action="{{('/crear_sector')}}"
          {% endif %}
                 name="nuevo">
                <label class=" form-label"  for="nombre">Nombre del sector: *</label>
                <input class=" form-control"  type="text" name="nombre" 
                        {% if sector is defined %} 
                                value="{{sector.nombre}}" 
                        {% endif %} required>
                <input class=" mt-3 mb-3 w-100"  type="submit" 
                        {% if sector is defined %} 
                                value="Editar sector" 
                        {% else %}
                                value="Crear sector"
                        {% endif %}
                 name="crear">
        </form>

        <a href="{{('/sectores')}}"><button>Atrás</button></a>

        
        {% endblock %}
        {% block javascripts %}

        {% endblock %}

backend/miproyecto/templates/nuevo_usuario.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{parent()}}
{% endblock %}

{% block body %}
    
    {% if usuario is defined %}
    <h5>EDITAR USUARIO</h5>
    {% else %}
    <h5>NUEVO USUARIO</h5>
    {% endif %}
    
    <form class="formu" 
    {% if usuario is defined %}
    action="{{ path ('modifico_usuario' , { 'id' : usuario.id } )}}"
    {% else %}
     action="{{('/crear_usuario')}}"
    {% endif %}>
        <label class=" form-label"  for="usuario" >Usuario: * </label>
        <input class=" form-control" type="text" name="usuario"
            {% if usuario is defined %}
                value="{{ usuario.usuario }}"
            {% endif %}
         required >
        <label class=" form-label" for="nombre">Nombre: * </label>
        <input class=" form-control" type="text" name="nombre" 
            {% if usuario is defined %}
                value="{{ usuario.nombre }}"
            {% endif %}
        required>
        <label class=" form-label" for="apellidos">Apellidos: *</label>
        <input class=" form-control" type="text" name="apellidos" 
            {% if usuario is defined %}
                value="{{ usuario.apellidos }}"
            {% endif %}
        required>
        <label class=" form-label" for="email"> Email: *</label>
        <input class=" form-control" type="text" name="email" 
            {% if usuario is defined %}
                value="{{ usuario.email }}"
            {% endif %}
        required>
        <label class=" form-label" for="pass"> Contraseña: *</label>
        <input class=" form-control" type="password" name="pass" 
        required>
        
        <label class=" form-label" for="rol"> Rol del usuario: *</label>
        <select class=" form-control"  name="rol">
        {% if usuario is defined %}
                {{ usuario.email }}
            {% endif %}
            <option value="cliente">Cliente</option>
            <option value="admin">Administrador</option>
        </select>

        <input class="mt-3 mb-3 w-100" type="submit" value="Crear usuario">
    </form>

    
        <a href="{{('/usuarios')}}"><button>Atrás</button></a>
{% endblock %}

{% block javascripts %}
   
{% endblock %}

backend/miproyecto/templates/sectores.html.twig
{% extends 'base.html.twig' %}
        {% block stylesheets %}
        {{parent()}}

        {% endblock %}


        {% block body %}


        <h5>LISTADO DE SECTORES </h5>
        
        
        
        <table class="table-responsive-sm table">
                <thead class="table-title">
                        <tr>
                                <th colspan="2">Sectores</th>
                        </tr>
                </thead>
                <tbody>
                {% for sector in sectores %}
                        {% if app.session.get('rol') == 'admin' %}
                        <tr>
                                <td> {{ sector.nombre }} </td>
                        {% else %}
                                {% for mi_sector in mis_sectores %}
                                        {% if mi_sector.idSector == sector.id %}
                                                <tr>
                                                <td> {{ sector.nombre }} </td>
                                        {% endif %}
                                {% endfor %}
                        {% endif %}
                                <!-- solo admin -->
                                {% if app.session.get('rol') == 'admin' %}
                                        <td> <a href="{{ path ('editar_sector' , {'id' : sector.id }) }}"><button class="btn btn-secondary"> <i class="fa fa-edit"></i> Editar</button></a> 
                                        <a href="{{ path ('eliminar_sector' , {'id' : sector.id }) }}"><button class="btn btn-secondary"> <i class="fa fa-minus-circle "></i> Eliminar</button></a>
                                        </td>
                                {% endif %}
                        </tr>
                {% endfor %}
                </tbody>
        </table>

        {% if app.session.get('rol') == 'admin' %}
        <a href="{{('/nuevo_sector')}}"><button>Nuevo sector</button></a>
        {% endif %}

        
        {% endblock %}
        {% block javascripts %}

        {% endblock %}

backend/miproyecto/templates/usuarios.html.twig
{% extends 'base.html.twig' %}
        {% block stylesheets %}
        {{parent()}}

        {% endblock %}



        {% block body %}
        
        <h5> LISTADO DE USUARIOS </h5>
        
        
        <table class="table-responsive-sm table " >
                <thead class="table-title">
                        <tr>
                            <th>Usuario</th>
                            <th>Nombre</th>
                            <th>Apellidos</th>
                            <th>Email</th>
                            <th>Sectores</th>
                            <th>Rol</th>
                             <th></th>
                        </tr>
                </thead>
                <tbody>
                        {% for usuario in usuarios %}
                                <tr>
                                    <td>{{ usuario.usuario }} </td>
                                    <td>{{ usuario.nombre }} </td>
                                    <td>{{ usuario.apellidos }} </td>
                                    <td>{{ usuario.email }}  </td>
                                    <td><ul class="sectores-list">
                                    {% for usuariosector in usuariossectores %}
                                        {% if usuariosector.idUsuario == usuario.id %}
                                                {% for sector in sectores %}
                                                        {% if sector.id == usuariosector.idSector %}
                                                        <li class="sector-list">{{ sector.nombre }}
                                                        <a href="{{ path ('quitar_sector' , {'id' : usuariosector.id }) }}">
                                                                <button class=" btn" class="btn"><i class="fa fa-minus-circle"></i></button></a>
                                                        </li> 
                                                        {% endif %}
                                                {% endfor %}
                                        {% endif %}
                                     {% endfor %}
                                     <a href="{{ path ('asignar_sector' , {'id' : usuario.id }) }}"><button class=" btn btn-secondary" ><i class="fa fa-plus"></i> Asignar</button></a>
                                     </ul></td>
                                    <td>{{ usuario.rol }} </td>
                                    <!-- solo admin -->
                                {% if app.session.get('rol') == 'admin' %}
                                        <td> <a href="{{ path ('editar_usuario' , {'id' : usuario.id }) }}"><button class=" btn btn-secondary"> <i class="fa fa-edit"></i> Editar</button></a> 
                                        <a href="{{ path ('eliminar_usuario' , {'id' : usuario.id }) }}"><button class=" btn btn-secondary" <i class="fa fa-minus-circle "></i> Eliminar</button></a>
                                        </td>
                                {% endif %}
                                </tr> 
                        {% endfor %}  
                </tbody>
        </table>


        {% if app.session.get('rol') == 'admin' %}
                <a href="{{('/nuevo_usuario')}}"><button>Nuevo usuario</button></a>
        {% endif %}

        {% endblock %}
        {% block javascripts %}

        {% endblock %}